### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by cv0cv0** [weekitmo/flutter-assets-gen#1]
[flutter-assets-gen.generate] Error: ENOENT: no such file or directory, chdir 'D:\Software\Microsoft VS Code' -> '/d:/Code/Flutter/flutter_sxtapp'

**Comment by weekitmo** [comment]
@cv0cv0 ok, cause i didn't specifically debug win system, i will deal with it tomorrow

**Comment by weekitmo** [comment]
please upgrade vsix@0.0.9
