### ISSUE TITLE
Prefer single quotes for paths

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [weekitmo/flutter-assets-gen#11]
According to dart [linter-rules](https://dart.dev/tools/linter-rules/prefer_single_quotes), we should prefer using single quotes instead of double quotes for strings.

Can we please either follow this, or write `// ignore_for_file: prefer_single_quotes` as the first line of the generated file to ignore this lint and stop the IDE from showing warnings?

**Comment by weekitmo** [comment]
Version 0.1.6 will be released later
