### ISSUE TITLE
[Feature] Add package_name field to be able to use assets inside packages without assigning package name to every image widget.

### ISSUE THREAD

**Issue by abdelrahman-atef1** [weekitmo/flutter-assets-gen#13]
### Feature: Add `package_name` Field to `flutter_assets` configs for Asset Management

**Explanation:**

In Flutter, when using assets from a package, developers currently need to specify the package name for each asset individually in the `Image` widget or similar widgets. This can be repetitive and inefficient, especially when using multiple assets from the same package.

The proposed feature introduces a `package_name` field that can be added to the `pubspec.yaml` file under the `flutter_assets:` section. This field would allow developers to define the package name globally. As a result, assets could be used without repeatedly specifying the package name, improving code cleanliness and reducing redundancy.

For example, instead of writing:

```dart
Image.asset('assets/images/icon.png', package: 'my_package')
```

each time an asset is used, the `package_name` could be set once in the `pubspec.yaml`:

```yaml
flutter_assets:
  package_name: my_package
```

Then, this would resolve to:

```dart
String icon = 'packages/my_package/assets/images/icon.png';
```

**Comment by weekitmo** [comment]
Nice suggestion.
