### ISSUE TITLE
生成的Key没有完全按照驼峰命名规则

### ISSUE THREAD

**Issue by tourdt** [weekitmo/flutter-assets-gen#3]
当assets有多级子目录时，生成的资源Key，没有完全按照驼峰命名规则，如：
static const String imagesuserVip = "assets/images/user/vip.png";

images目录下，新建了子目录user, 生成的key为：imagesuserXxx
希望有时间的时候能优化一下，谢谢

**Comment by weekitmo** [comment]
更新0.1.2
