### ISSUE TITLE
classname not worked as expected shown in readme.md

### ISSUE THREAD

**Issue by codersangam** [weekitmo/flutter-assets-gen#7]
I used the code from readme and generated the assets but class name not get changed as expected. screenshot is attached below:
<img width="1259" alt="Screenshot 2024-02-08 at 22 26 22" src="https://github.com/weekitmo/flutter-assets-gen/assets/66767187/02ec2b1d-93d8-4732-9150-876bff32039b">

**Comment by zenxx** [comment]
class_name -> classname

**Comment by weekitmo** [comment]
> class_name -> classname

thx, maybe I should take the time to change the README file.
