### ISSUE TITLE
Same images different extension errors

### ISSUE THREAD

**Issue by fretelweb** [weekitmo/flutter-assets-gen#9]
The name 'imagesPlaces' is already defined. Try renaming one of the declarations.

```
 /// Assets for imagesPlaces
/// assets/images/places.svg
static const String imagesPlaces = "assets/images/places.svg";

/// Assets for imagesPlaces
/// assets/images/places.jpeg
static const String imagesPlaces = "assets/images/places.jpeg";
```

**Comment by weekitmo** [comment]
I don't have any good ideas to deal with such a problem, after all, this expansion with a different file extension can lead to too long variable names
